  public enum CommonSymptom {
    AURA,
    NAUSEA_VOMITING,
    LIGHT_SENSITIVITY,
    SOUND_SENISITIVITY,
    SMELL_SENSITIVITY,
    VISION_DISTURBANCE,
    TEARY_REDEYES,
    SINUS_CONGESTION,
    NECK_PAIN
  }